/**
 * Roadmap — the commitments layer (Phase 12).
 *
 * Everything derivable about the products was already derived: the registry
 * regenerates from Nexus's own module manifests, verify-claims resolves cited
 * paths, drift-check watches facts drift from evidence. The one thing no repo
 * can tell you is the date you promised. This module holds those dates.
 *
 * Split, deliberately:
 *   authored  → operations/roadmap/<slug>.md  (target, evidence, definition of done)
 *   derived   → operations/roadmap/_status.md (regenerated by scripts/roadmap-check.ts)
 *
 * There is NO `status:` field anywhere in the authored files. A hand-maintained
 * status column is the exact thing that goes stale and lies — `done:` is a fact
 * recorded once, and every state between now and then is computed. This module
 * only joins the two halves; the computation lives in `deriveState` so the
 * script and the page can never disagree about what "at-risk" means.
 */
import fs from 'fs/promises'
import path from 'path'
import matter from 'gray-matter'
import { PATHS } from './paths'

/** Evidence colder than this while a target is near means nobody is working. */
export const EVIDENCE_WARN_DAYS = 14
/** Cold this long with no near target is an initiative that has gone quiet. */
export const EVIDENCE_IDLE_DAYS = 30
/** A target this close is "now" — matches the Clock's window. */
export const TARGET_NEAR_DAYS = 14
/** `_status.md` older than this is not trustworthy; render unknown, never green. */
export const STATUS_STALE_DAYS = 10

export type RoadmapGroup = 'nexus' | 'internal' | 'web'
export type RoadmapKind = 'build' | 'handoff'

/**
 * Derived states, worst first. `unknown` is load-bearing: a repo that would not
 * fetch, or a `_status.md` that never ran, must never render as on-track.
 */
export type RoadmapState =
  | 'slipped' | 'at-risk' | 'unknown' | 'stranded'
  | 'idle' | 'no-target' | 'on-track' | 'active' | 'done'

/** Handoff lifecycle. `consumed` is the only state that means we got value. */
export type HandoffState = 'spec-sent' | 'pr-opened' | 'merged' | 'consumed' | 'unknown'

export interface EvidencePath {
  repo: string
  path: string
}

export interface RoadmapItem {
  slug: string
  name: string
  group: RoadmapGroup
  kind: RoadmapKind
  /** group `nexus` only — joins to operations/products/<slug>.md and the registry. */
  product?: string
  repos: string[]
  /** `handoff` only: who holds the ball. Pavan owns every roadmap; that is why
   *  there is no `owner` field — it would be a constant. This is what varies. */
  waitingOn?: string
  target?: string // YYYY-MM-DD
  done?: string   // YYYY-MM-DD — recorded once, never maintained
  evidence: EvidencePath[]
  handoff?: { spec?: string; landed?: string; consumedBy?: string }
  body: string

  // ── derived (joined from _status.md; undefined when it has not run) ──
  daysToTarget?: number
  /** Days since the last *human* commit touching any evidence path on origin. */
  evidenceAgeDays?: number
  lastEvidenceAt?: string
  handoffState?: HandoffState
  handoffAgeDays?: number
  state: RoadmapState
  /** Why the state is what it is — rendered verbatim, so it must read as prose. */
  reason: string
}

export interface RoadmapStatus {
  generatedAt?: string
  stale: boolean
  ran: boolean
  items: Record<string, DerivedEntry>
}

export interface DerivedEntry {
  slug: string
  evidenceAgeDays?: number | null
  lastEvidenceAt?: string | null
  handoffState?: HandoffState
  handoffAgeDays?: number | null
  /** Set when the repo could not be fetched or read — forces `unknown`. */
  error?: string
}

export function daysBetween(from: Date, toDate: string): number {
  const [y, m, d] = toDate.split('-').map(Number)
  const a = new Date(from.getFullYear(), from.getMonth(), from.getDate()).getTime()
  return Math.round((new Date(y, m - 1, d).getTime() - a) / 86_400_000)
}

/**
 * The single definition of "how are we doing" — imported by both the page and
 * roadmap-check, so the board and the generated report can never disagree.
 *
 * Order matters. `done` short-circuits; a missing derivation is `unknown`
 * before it is anything reassuring; a real slip outranks everything else.
 */
export function deriveState(
  item: Pick<RoadmapItem, 'kind' | 'target' | 'done'>,
  derived: DerivedEntry | undefined,
  statusRan: boolean,
  now = new Date()
): { state: RoadmapState; reason: string; daysToTarget?: number } {
  if (item.done) return { state: 'done', reason: `Done ${item.done}` }

  const daysToTarget = item.target ? daysBetween(now, item.target) : undefined

  // A slip is a fact about a date we set, knowable without any repo access.
  if (daysToTarget !== undefined && daysToTarget < 0) {
    return {
      state: 'slipped',
      reason: `Target ${item.target} passed ${-daysToTarget}d ago, not marked done`,
      daysToTarget,
    }
  }

  if (!statusRan) {
    return { state: 'unknown', reason: 'roadmap-check has not run', daysToTarget }
  }
  if (derived?.error) {
    return { state: 'unknown', reason: derived.error, daysToTarget }
  }

  if (item.kind === 'handoff') {
    const hs = derived?.handoffState ?? 'unknown'
    if (hs === 'unknown') return { state: 'unknown', reason: 'Handoff state not resolved', daysToTarget }
    if (hs === 'consumed') return { state: 'done', reason: 'Landed and consumed', daysToTarget }
    const age = derived?.handoffAgeDays
    // Shipped on their side and unused on ours is the worst handoff outcome:
    // it looks finished from every angle except the one that matters.
    if (hs === 'merged') {
      return {
        state: 'stranded',
        reason: age != null
          ? `Merged ${age}d ago, still not consumed here`
          : 'Merged, still not consumed here',
        daysToTarget,
      }
    }
    return {
      state: age != null && age >= EVIDENCE_IDLE_DAYS ? 'idle' : 'active',
      reason: age != null ? `${hs.replace('-', ' ')} — ${age}d ago` : hs.replace('-', ' '),
      daysToTarget,
    }
  }

  const age = derived?.evidenceAgeDays
  if (age == null) {
    return { state: 'unknown', reason: 'No evidence path resolved', daysToTarget }
  }

  if (daysToTarget !== undefined && daysToTarget <= TARGET_NEAR_DAYS) {
    return age >= EVIDENCE_WARN_DAYS
      ? {
          state: 'at-risk',
          reason: `Due in ${daysToTarget}d, no commits on the evidence path in ${age}d`,
          daysToTarget,
        }
      : { state: 'on-track', reason: `Due in ${daysToTarget}d, last commit ${age}d ago`, daysToTarget }
  }

  if (age >= EVIDENCE_IDLE_DAYS) {
    return {
      state: 'idle',
      reason: `No commits on the evidence path in ${age}d`,
      daysToTarget,
    }
  }

  if (daysToTarget === undefined) {
    return { state: 'no-target', reason: `Active (last commit ${age}d ago) but no target date set`, daysToTarget }
  }

  return { state: 'active', reason: `Last commit ${age}d ago, ${daysToTarget}d to target`, daysToTarget }
}

function str(v: unknown): string | undefined {
  return typeof v === 'string' && v.trim() ? v.trim() : undefined
}

/** Frontmatter dates parse as Date via YAML; normalize both spellings. */
function ymd(v: unknown): string | undefined {
  if (v instanceof Date && !isNaN(v.getTime())) {
    return `${v.getUTCFullYear()}-${String(v.getUTCMonth() + 1).padStart(2, '0')}-${String(v.getUTCDate()).padStart(2, '0')}`
  }
  const s = str(v)
  return s && /^\d{4}-\d{2}-\d{2}$/.test(s) ? s : undefined
}

function parseEvidence(v: unknown): EvidencePath[] {
  if (!Array.isArray(v)) return []
  return v.flatMap(e => {
    if (!e || typeof e !== 'object') return []
    const repo = str((e as Record<string, unknown>).repo)
    const p = str((e as Record<string, unknown>).path)
    return repo && p ? [{ repo, path: p }] : []
  })
}

/** Read `_status.md`'s frontmatter — the derived half. Absent is a legal state. */
export async function readStatus(): Promise<RoadmapStatus> {
  let raw: string
  try {
    raw = await fs.readFile(PATHS.roadmapStatus, 'utf-8')
  } catch {
    return { ran: false, stale: true, items: {} }
  }
  try {
    const { data } = matter(raw)
    const generatedAt = str(data.generated_at)
    const ageDays = generatedAt
      ? (Date.now() - new Date(generatedAt).getTime()) / 86_400_000
      : Infinity
    const items: Record<string, DerivedEntry> = {}
    for (const e of Array.isArray(data.checked) ? data.checked : []) {
      if (!e || typeof e !== 'object') continue
      const slug = str((e as Record<string, unknown>).slug)
      if (!slug) continue
      const r = e as Record<string, unknown>
      items[slug] = {
        slug,
        evidenceAgeDays: typeof r.evidence_age_days === 'number' ? r.evidence_age_days : null,
        lastEvidenceAt: str(r.last_evidence_at) ?? null,
        handoffState: str(r.handoff_state) as HandoffState | undefined,
        handoffAgeDays: typeof r.handoff_age_days === 'number' ? r.handoff_age_days : null,
        error: str(r.error),
      }
    }
    return {
      generatedAt,
      ran: true,
      // A check that has not run in over a week is not evidence of health.
      stale: !isFinite(ageDays) || ageDays > STATUS_STALE_DAYS,
      items,
    }
  } catch {
    return { ran: false, stale: true, items: {} }
  }
}

/** Worst first — the board is read top-down and the top must be the problem. */
const STATE_RANK: Record<RoadmapState, number> = {
  slipped: 0, stranded: 1, 'at-risk': 2, unknown: 3,
  idle: 4, 'no-target': 5, 'on-track': 6, active: 7, done: 8,
}

export async function listRoadmap(now = new Date()): Promise<RoadmapItem[]> {
  let names: string[]
  try {
    names = await fs.readdir(PATHS.roadmap)
  } catch {
    return []
  }
  // `_`-prefixed is derived, README.md is documentation — neither is a
  // commitment. (channels.ts excludes tracker.md for the same reason.)
  const files = names.filter(n =>
    n.endsWith('.md') && !n.startsWith('_') && !n.startsWith('.') && n !== 'README.md')
  const status = await readStatus()

  const items = await Promise.all(files.map(async (filename): Promise<RoadmapItem | null> => {
    let raw: string
    try {
      raw = await fs.readFile(path.join(PATHS.roadmap, filename), 'utf-8')
    } catch {
      return null
    }
    try {
      const { data, content } = matter(raw)
      const slug = str(data.slug) ?? filename.replace(/\.md$/, '')
      const group = (str(data.group) ?? 'internal') as RoadmapGroup
      const kind = (str(data.kind) ?? 'build') as RoadmapKind
      const h = (data.handoff ?? {}) as Record<string, unknown>
      const base = {
        kind,
        target: ymd(data.target),
        done: ymd(data.done),
      }
      const { state, reason, daysToTarget } = deriveState(base, status.items[slug], status.ran, now)
      const derived = status.items[slug]
      return {
        slug,
        name: str(data.name) ?? slug,
        group,
        kind,
        product: str(data.product),
        repos: Array.isArray(data.repos) ? data.repos.filter((r): r is string => typeof r === 'string') : [],
        waitingOn: str(data.waiting_on),
        target: base.target,
        done: base.done,
        evidence: parseEvidence(data.evidence),
        handoff: kind === 'handoff'
          ? { spec: str(h.spec), landed: str(h.landed), consumedBy: str(h.consumed_by) }
          : undefined,
        body: content.trim(),
        daysToTarget,
        evidenceAgeDays: derived?.evidenceAgeDays ?? undefined,
        lastEvidenceAt: derived?.lastEvidenceAt ?? undefined,
        handoffState: derived?.handoffState,
        handoffAgeDays: derived?.handoffAgeDays ?? undefined,
        state,
        reason,
      }
    } catch {
      return null // corrupt frontmatter — skip the file, never the page
    }
  }))

  return items
    .filter((i): i is RoadmapItem => i !== null)
    .sort((a, b) =>
      STATE_RANK[a.state] - STATE_RANK[b.state] ||
      (a.target ?? '9999').localeCompare(b.target ?? '9999') ||
      a.name.localeCompare(b.name)
    )
}

/** The states that belong in front of Pavan rather than on a page he visits. */
export function roadmapAlerts(items: RoadmapItem[]): RoadmapItem[] {
  return items.filter(i => i.state === 'slipped' || i.state === 'at-risk' || i.state === 'stranded')
}
